### ISSUE TITLE
Mach3 Plugin don't work

### ISSUE THREAD

**Issue by sallos** [regeg/ArdunioTHC#1]
Hi,

I found your project, it is very interesting.
you can write to you via e-mail?

The Mach3 plugin not to work

**Comment by regeg** [comment]
I haven't been working on this or using the CNC for a while (other projects taking priority).

I had the plug-in working.  The best that I can recall is that the working code wasn't in the repo directory.  I've pushed what I think is the correct code.  Give that a try.

**Comment by sallos** [comment]
Thanks,

the dll ist the old. Can you complile? I haven't VB on my pc.

**Comment by regeg** [comment]
Try the dll in the "Release" directory that I just added.

**Comment by sallos** [comment]
Thanks it works.

Where do you come from? 

Do you have a Micro PCB?

**Comment by regeg** [comment]
The plasma screen for Mach was missing.  It has just been added.  It is "PlasmaTHC.set". There were issues with the screen designer and I get a different appearance in the screen designer from Mach.  Not sure what's going on with that.
